import { PhoneModel } from "./types";

export const PHONE_MODELS: PhoneModel[] = [
  {
    id: "samsung-s24",
    brand: "Samsung",
    name: "Galaxy S24 Ultra",
    image: "https://picsum.photos/seed/s24/400/600",
    category: "trending",
    prices: { FRP: 5, MDM: 10, SIM: 8 },
    unlockTypes: ["light", "hard"],
  },
  {
    id: "iphone-15",
    brand: "Apple",
    name: "iPhone 15 Pro",
    image: "https://picsum.photos/seed/iphone15/400/600",
    category: "most-unlocked",
    prices: { SIM: 15, MDM: 20, iCloud: 25 },
    unlockTypes: ["light"],
  },
  {
    id: "pixel-8",
    brand: "Google",
    name: "Pixel 8 Pro",
    image: "https://picsum.photos/seed/pixel8/400/600",
    category: "trending",
    prices: { FRP: 5, BOOTLOADER: 12 },
    unlockTypes: ["light", "hard"],
  },
  {
    id: "xiaomi-14",
    brand: "Xiaomi",
    name: "Xiaomi 14 Ultra",
    image: "https://picsum.photos/seed/xiaomi14/400/600",
    category: "most-unlocked",
    prices: { FRP: 5, MDM: 10, SIM: 8 },
    unlockTypes: ["light", "hard"],
  },
  {
    id: "samsung-z-fold-6",
    brand: "Samsung",
    name: "Galaxy Z Fold 6",
    image: "https://picsum.photos/seed/fold6/400/600",
    category: "coming-soon",
    prices: { FRP: 8, MDM: 15 },
    unlockTypes: ["hard"],
  },
  {
    id: "pixel-9",
    brand: "Google",
    name: "Pixel 9 Pro",
    image: "https://picsum.photos/seed/pixel9/400/600",
    category: "coming-soon",
    prices: { FRP: 5, BOOTLOADER: 15 },
    unlockTypes: ["hard"],
  },
  {
    id: "xiaomi-redmi-13",
    brand: "Xiaomi",
    name: "Redmi Note 13",
    image: "https://picsum.photos/seed/redmi13/400/600",
    category: "trending",
    prices: { "Mi Account": 10, FRP: 5 },
    unlockTypes: ["light", "hard"],
  },
  {
    id: "oneplus-12",
    brand: "OnePlus",
    name: "OnePlus 12",
    image: "https://picsum.photos/seed/oneplus12/400/600",
    category: "most-unlocked",
    prices: { FRP: 5, BOOTLOADER: 10 },
    unlockTypes: ["light", "hard"],
  },
  {
    id: "samsung-a54",
    brand: "Samsung",
    name: "Galaxy A54",
    image: "https://picsum.photos/seed/a54/400/600",
    category: "trending",
    prices: { FRP: 5, MDM: 8 },
    unlockTypes: ["light"],
  },
  {
    id: "huawei-p60",
    brand: "Huawei",
    name: "P60 Pro",
    image: "https://picsum.photos/seed/p60/400/600",
    category: "most-unlocked",
    prices: { FRP: 10 },
    unlockTypes: ["hard"],
  },
];
